const SUPABASE_URL="https://rocvqcqgbdohfwfkhncy.supabase.co";
const SUPABASE_KEY="sb_publishable_wStACVHPYgU82oxbsvAWTg_EdkHrQaF";
const supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const PHOTO_BUCKET="member-photos";
const LOGO_URL=new URL("poga-ksa-logo.png",location.href).href;
const SAUDI_FLAG_URL=new URL("saudi-flag.svg",location.href).href;
const PH_FLAG_URL=new URL("philippines-flag.svg",location.href).href;

const $=id=>document.getElementById(id);
const loginSection=$("loginSection"),loginForm=$("loginForm"),loginEmail=$("loginEmail"),loginPassword=$("loginPassword"),loginButton=$("loginButton"),loginError=$("loginError");
const dashboardSection=$("dashboardSection"),adminEmail=$("adminEmail"),logoutButton=$("logoutButton");
const memberForm=$("memberForm"),formTitle=$("formTitle"),memberId=$("memberId"),fullName=$("fullName"),passportNumber=$("passportNumber"),birthday=$("birthday"),country=$("country"),address=$("address"),contact=$("contact"),emergencyContact=$("emergencyContact"),emergencyNumber=$("emergencyNumber"),status=$("status"),photo=$("photo"),photoPreview=$("photoPreview"),saveButton=$("saveButton"),cancelEditButton=$("cancelEditButton");
const searchInput=$("searchInput"),membersTableBody=$("membersTableBody"),printAllMembersButton=$("printAllMembersButton");
const memberDetailsModal=$("memberDetailsModal"),closeDetailsButton=$("closeDetailsButton"),detailsPhoto=$("detailsPhoto"),detailsMemberId=$("detailsMemberId"),detailsFullName=$("detailsFullName"),detailsPassport=$("detailsPassport"),detailsBirthday=$("detailsBirthday"),detailsCountry=$("detailsCountry"),detailsContact=$("detailsContact"),detailsAddress=$("detailsAddress"),detailsEmergencyPerson=$("detailsEmergencyPerson"),detailsEmergencyNumber=$("detailsEmergencyNumber"),detailsStatus=$("detailsStatus"),detailsPrintButton=$("detailsPrintButton"),detailsEditButton=$("detailsEditButton"),detailsCloseButton=$("detailsCloseButton");

let editingId=null,currentPhotoUrl=null,selectedPhotoFile=null,currentDetailsMemberId=null;

const s=document.createElement("style");
s.textContent=`.action-buttons{display:flex;flex-wrap:wrap;gap:6px;align-items:center}.action-buttons button{border:0;border-radius:6px;padding:8px 12px;font-size:14px;font-weight:600;cursor:pointer}.view-button{background:#2563eb!important;color:#fff!important}.edit-button{background:#166534!important;color:#fff!important}.delete-button{background:#dc2626!important;color:#fff!important}`;
document.head.appendChild(s);

function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function date(v){if(!v)return"-";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-US",{year:"numeric",month:"short",day:"numeric"})}
function pathOf(v){if(!v)return null;v=String(v).trim();if(!/^https?:\/\//i.test(v))return v;try{const p=new URL(v).pathname;for(const m of [`/storage/v1/object/public/${PHOTO_BUCKET}/`,`/storage/v1/object/sign/${PHOTO_BUCKET}/`,`/storage/v1/object/download/${PHOTO_BUCKET}/`])if(p.includes(m))return decodeURIComponent(p.split(m)[1]);}catch(e){}return null}
async function signed(v){const p=pathOf(v);if(!p)return null;const{data,error}=await supabaseClient.storage.from(PHOTO_BUCKET).createSignedUrl(p,3600);if(error){console.error(error);return null}return data?.signedUrl||null}
async function upload(f){if(!f)return null;const ext=(f.name.split(".").pop()||"jpg").toLowerCase();const name=`member_${Date.now()}_${Math.random().toString(36).slice(2,10)}.${ext==="jpeg"?"jpg":ext}`;const{error}=await supabaseClient.storage.from(PHOTO_BUCKET).upload(name,f,{cacheControl:"3600",upsert:false,contentType:f.type});if(error)throw error;return name}

async function checkAuth(){const{data:{session}}=await supabaseClient.auth.getSession();session?showDashboard(session.user):showLogin()}
function showLogin(){loginSection?.classList.remove("hidden");dashboardSection?.classList.add("hidden");if(adminEmail)adminEmail.textContent=""}
async function showDashboard(u){loginSection?.classList.add("hidden");dashboardSection?.classList.remove("hidden");if(adminEmail)adminEmail.textContent=u?.email||"";await loadMembers()}
loginForm?.addEventListener("submit",async e=>{e.preventDefault();loginError.textContent="";loginButton.disabled=true;loginButton.textContent="Logging in...";const{data,error}=await supabaseClient.auth.signInWithPassword({email:loginEmail.value.trim(),password:loginPassword.value});loginButton.disabled=false;loginButton.textContent="Login";if(error){loginError.textContent=error.message;return}if(data.session)await showDashboard(data.user)});
logoutButton?.addEventListener("click",async()=>{const{error}=await supabaseClient.auth.signOut();if(error)alert("Logout failed: "+error.message);else showLogin()});
supabaseClient.auth.onAuthStateChange(async(e,session)=>{if(e==="SIGNED_IN"&&session)await showDashboard(session.user);if(e==="SIGNED_OUT")showLogin()});

photo?.addEventListener("change",()=>{const f=photo.files[0];selectedPhotoFile=null;if(!f)return;if(!f.type.startsWith("image/")){alert("Please select an image file.");photo.value="";return}if(f.size>5*1024*1024){alert("Photo must be 5MB or smaller.");photo.value="";return}selectedPhotoFile=f;const r=new FileReader();r.onload=e=>photoPreview.innerHTML=`<img src="${e.target.result}" alt="Photo Preview" class="member-photo">`;r.readAsDataURL(f)});

function formData(photoUrl=null){return{member_id:memberId.value.trim(),full_name:fullName.value.trim(),passport_number:passportNumber.value.trim(),birthday:birthday.value,country_of_work:country.value||null,address:address.value.trim(),contact_number:contact.value.trim(),emergency_contact_person:emergencyContact.value.trim(),emergency_contact_number:emergencyNumber.value.trim(),membership_status:status.value,photo_url:photoUrl}}

memberForm?.addEventListener("submit",async e=>{e.preventDefault();saveButton.disabled=true;saveButton.textContent=editingId?"Updating...":"Saving...";try{if(!editingId){if(!selectedPhotoFile){alert("Please select a member photo.");return}const p=await upload(selectedPhotoFile),{error}=await supabaseClient.from("members").insert([formData(p)]);if(error)throw error;alert("Member added successfully.")}else{let p=currentPhotoUrl;if(selectedPhotoFile)p=await upload(selectedPhotoFile);const{error}=await supabaseClient.from("members").update(formData(p)).eq("id",editingId);if(error)throw error;alert("Member updated successfully.")}resetForm();await loadMembers()}catch(err){console.error(err);alert("Error: "+err.message)}finally{saveButton.disabled=false;saveButton.textContent="Save Member"}});

async function loadMembers(){const{data,error}=await supabaseClient.from("members").select("*");if(error){alert("Unable to load members: "+error.message);return}data.sort((a,b)=>(parseInt(a.member_id,10)||0)-(parseInt(b.member_id,10)||0));await display(data)}
async function display(ms){membersTableBody.innerHTML="";if(!ms?.length){membersTableBody.innerHTML='<tr><td colspan="8" class="empty">No members found.</td></tr>';return}for(const m of ms){let ph='<div class="no-photo">No Photo</div>';if(m.photo_url){const u=await signed(m.photo_url);if(u)ph=`<img src="${esc(u)}" alt="Member Photo" class="member-photo">`}const r=document.createElement("tr");r.innerHTML=`<td>${ph}</td><td>${esc(m.member_id||"")}</td><td>${esc(m.full_name||"")}</td><td>${esc(m.passport_number||"")}</td><td>${date(m.birthday)}</td><td>${esc(m.contact_number||"")}</td><td><span class="status">${esc(m.membership_status||"")}</span></td><td><div class="action-buttons"><button class="view-button" onclick="viewMemberDetails('${m.id}')">View Details</button><button class="edit-button" onclick="editMember('${m.id}')">Edit</button><button class="delete-button" onclick="deleteMember('${m.id}')">Delete</button></div></td>`;membersTableBody.appendChild(r)}}

async function viewMemberDetails(id){const{data:m,error}=await supabaseClient.from("members").select("*").eq("id",id).single();if(error){alert("Unable to load member details: "+error.message);return}currentDetailsMemberId=m.id;detailsPhoto.innerHTML='<div class="no-photo">Loading Photo...</div>';if(m.photo_url){const u=await signed(m.photo_url);detailsPhoto.innerHTML=u?`<img src="${esc(u)}" alt="Member Photo">`:'<div class="no-photo">Photo unavailable</div>'}else detailsPhoto.innerHTML='<div class="no-photo">No Photo</div>';detailsMemberId.textContent=m.member_id||"-";detailsFullName.textContent=m.full_name||"-";detailsPassport.textContent=m.passport_number||"-";detailsBirthday.textContent=date(m.birthday);detailsCountry.textContent=m.country_of_work||"-";detailsContact.textContent=m.contact_number||"-";detailsAddress.textContent=m.address||"-";detailsEmergencyPerson.textContent=m.emergency_contact_person||"-";detailsEmergencyNumber.textContent=m.emergency_contact_number||"-";detailsStatus.textContent=m.membership_status||"-";memberDetailsModal.classList.remove("hidden")}

detailsEditButton?.addEventListener("click",async()=>{if(!currentDetailsMemberId)return;const idToEdit=currentDetailsMemberId;closeDetails();await editMember(idToEdit)});
detailsPrintButton?.addEventListener("click",()=>currentDetailsMemberId&&printMemberDetails(currentDetailsMemberId));
function closeDetails(){memberDetailsModal.classList.add("hidden");currentDetailsMemberId=null}
closeDetailsButton?.addEventListener("click",closeDetails);detailsCloseButton?.addEventListener("click",closeDetails);
memberDetailsModal?.addEventListener("click",e=>{if(e.target===memberDetailsModal)closeDetails()});

async function editMember(id){if(!id){alert("Invalid member ID.");return}const{data:m,error}=await supabaseClient.from("members").select("*").eq("id",id).single();if(error){alert("Unable to load member: "+error.message);return}editingId=m.id;formTitle.textContent="Edit Member";memberId.value=m.member_id||"";fullName.value=m.full_name||"";passportNumber.value=m.passport_number||"";birthday.value=m.birthday||"";country.value=m.country_of_work||"";address.value=m.address||"";contact.value=m.contact_number||"";emergencyContact.value=m.emergency_contact_person||"";emergencyNumber.value=m.emergency_contact_number||"";status.value=m.membership_status||"Active";currentPhotoUrl=m.photo_url||null;selectedPhotoFile=null;photo.value="";if(m.photo_url){const u=await signed(m.photo_url);photoPreview.innerHTML=u?`<img src="${esc(u)}" alt="Current Member Photo" class="member-photo">`:'<div class="no-photo">Photo unavailable</div>'}else photoPreview.innerHTML='<div class="no-photo">No Photo</div>';saveButton.textContent="Update Member";cancelEditButton.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})}
cancelEditButton?.addEventListener("click",resetForm);

async function deleteMember(id){if(!confirm("Are you sure you want to delete this member?"))return;const{error}=await supabaseClient.from("members").delete().eq("id",id);if(error){alert("Unable to delete member: "+error.message);return}alert("Member deleted successfully.");await loadMembers()}

searchInput?.addEventListener("input",async()=>{const q=searchInput.value.trim();if(!q)return loadMembers();const{data,error}=await supabaseClient.from("members").select("*").or(`member_id.ilike.%${q}%,full_name.ilike.%${q}%,passport_number.ilike.%${q}%,contact_number.ilike.%${q}%`);if(error){console.error(error);return}data.sort((a,b)=>(parseInt(a.member_id,10)||0)-(parseInt(b.member_id,10)||0));await display(data)});

function resetForm(){editingId=null;currentPhotoUrl=null;selectedPhotoFile=null;memberForm.reset();status.value="Active";formTitle.textContent="Add Member";saveButton.textContent="Save Member";cancelEditButton.classList.add("hidden");photoPreview.innerHTML="";photo.value="";currentDetailsMemberId=null}

function printWindow(html){const w=window.open("","_blank","width=1000,height=900");if(!w){alert("Please allow pop-ups to print.");return}w.document.write(html);w.document.close()}
async function printMemberDetails(id){const{data:m,error}=await supabaseClient.from("members").select("*").eq("id",id).single();if(error){alert("Unable to load member for printing: "+error.message);return}const u=m.photo_url?await signed(m.photo_url):null;printWindow(`<!doctype html><html><head><title>POGA KSA - Member Record</title><style>body{font-family:Arial;padding:25px;color:#123b2a}.head{text-align:center;border-bottom:3px solid #166534;padding-bottom:15px}.brand{display:flex;justify-content:center;align-items:center;gap:10px}.logo{width:80px;height:80px;object-fit:contain}.flag{width:45px;height:30px;object-fit:cover}.top{display:flex;gap:25px;margin-top:25px}.photo{width:150px;height:180px;border:1px solid #aaa;display:flex;align-items:center;justify-content:center}.photo img{width:100%;height:100%;object-fit:cover}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:20px}.f{border-bottom:1px solid #ccc;padding:8px}.full{grid-column:1/-1}.l{display:block;font-size:12px;font-weight:bold}.v{font-size:16px;font-weight:600}</style></head><body><div class="head"><div class="brand"><img class="flag" src="${SAUDI_FLAG_URL}"><img class="logo" src="${LOGO_URL}"><img class="flag" src="${PH_FLAG_URL}"></div><h1>POGA KSA CHAPTER</h1><h2>Individual Member Record</h2></div><div class="top"><div class="photo">${u?`<img src="${esc(u)}">`:"No Photo"}</div><div><h2>${esc(m.full_name||"-")}</h2><div class="f"><span class="l">Member ID</span><span class="v">${esc(m.member_id||"-")}</span></div></div></div><div class="grid">${field("Full Name",m.full_name)}${field("Passport Number",m.passport_number)}${field("Birthday",date(m.birthday))}${field("Country of Work Abroad",m.country_of_work)}${field("Philippine Address",m.address,true)}${field("Contact Number",m.contact_number)}${field("Emergency Contact Person",m.emergency_contact_person)}${field("Emergency Contact Number",m.emergency_contact_number)}${field("Membership Status",m.membership_status)}</div><script>onload=()=>setTimeout(()=>print(),500)</script></body></html>`)}
function field(label,value,full=false){return`<div class="f ${full?"full":""}"><span class="l">${label}</span><span class="v">${esc(value||"-")}</span></div>`}

async function printAllMembers(){const{data:ms,error}=await supabaseClient.from("members").select("*");if(error){alert("Unable to load members for printing: "+error.message);return}ms.sort((a,b)=>(parseInt(a.member_id,10)||0)-(parseInt(b.member_id,10)||0));const rows=ms.map((m,i)=>`<tr><td>${i+1}</td><td>${esc(m.full_name||"-")}</td><td>${esc(m.passport_number||"-")}</td><td>${esc(m.address||"-")}</td><td>${esc(m.contact_number||"-")}</td></tr>`).join("");printWindow(`<!doctype html><html><head><title>POGA KSA - Overall Members</title><style>body{font-family:Arial;padding:20px}.head{text-align:center;border-bottom:3px solid #166534;padding-bottom:12px}.brand{display:flex;justify-content:center;gap:10px;align-items:center}.logo{width:70px;height:70px;object-fit:contain}.flag{width:45px;height:30px;object-fit:cover}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #999;padding:8px;text-align:left}th{background:#eee}</style></head><body><div class="head"><div class="brand"><img class="flag" src="${SAUDI_FLAG_URL}"><img class="logo" src="${LOGO_URL}"><img class="flag" src="${PH_FLAG_URL}"></div><h1>POGA KSA CHAPTER</h1><h2>Overall Member Records</h2></div><p><b>Total Members: ${ms.length}</b></p><table><thead><tr><th>#</th><th>Full Name</th><th>Passport #</th><th>Address sa Pinas</th><th>CP #</th></tr></thead><tbody>${rows||"<tr><td colspan='5'>No records</td></tr>"}</tbody></table><script>onload=()=>setTimeout(()=>print(),500)</script></body></html>`)}

printAllMembersButton?.addEventListener("click",printAllMembers);
checkAuth();
